language: ruby
virt: lxd
rvm:
- 2.5.3
dist: xenial
sudo: required
install:
- sudo apt-get update
- sudo apt-get install lua5.1 luarocks p7zip-full python-pip
- sudo pip install sphinx sphinx_rtd_theme
- sudo luarocks install penlight
- gem install github_changelog_generator
script:
- bash travis.sh
notifications:
  email:
    on_failure: always
    on_success: change
env:
  global:
  - GH_REF=github.com/svof/svof.git
  - GH_USER=svof-machine-account
  - secure: "UZ3zfIUNG526fjNP0QgBtcQJh0QuH+JdMe1j/aHYJmMvKvQK24Tn1sFgpR5C8vYiHXIvGLBDZNCXipKuQLsLC0dZ+Rx9OMkefUDdq0gDIcAntwDYnzF4Z6kAKRS9qyJbobl7TfaHM3iC+oN2u4MAzQeA1Sv5i1PgqzfKgG+jfRQXh0LQsnpASiLhKGMESifb0O6wrPQeK+6+5LwyAiYIsMlF3ZHUiZai57mTYfPoYiHDiWxFO26HzxAuU5bDXs12rlRUQeK61IODtGk+5jaymmQvzI6RuVWz+OPT5iH8l5p68fWgyDot/mjlDP6zr1k1LeNyFpVmJs+MdCqNZy7tbr/4NDThfzgaR6m4Ji6hXdW8Pcl0FhfAzjj63x5kJFPvBhyIvbWkpEA6UujyalXLTXAvr9m1WMO4JXAZcKzSkwaavOmC2PITf5Rr2FUpbBBRcZEHb9hdqYt00tkGYEfoVLwGuXImiez0cWYU8D/hUtHrF75eViTh3VQ4yeg3X9lotsxGGchTMTGhPIhe7wc55p60GLeewOukwrskrM6NTBEZuVeWBCtc8pFZy3AAYt85V/8Y/WMzjpmWh13s2SdBkA/Uhd/kUiceHUpA5Kmyu2XMgw0iheRCHWkd6v7bw7Or5Ko0d0wCS/t57l4KBjMybpDt99a6PqyeB7UZ8R5Xx+o="
deploy:
  provider: releases
  file_glob: true
  file: output/*.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "Jagz3AOPnBCDMw51Mo6a3u6GKK58VYIykuPo0rf5zQp1m9AlAKmLh682U/gFv5PcMXPiBoq1aqPsA33RL3UAlJ6L12o18hN6QAFANt4ciJ2/mLL2lV3YPzYQkJR/wUO4OoIqntcrpUb4eWfJgk0KWkpvxjJYqjL/ukky2zH7IU20kgvwbhCIHogNV0iXap9lPB5GVrkP3V0k4fxESN86kU+uAbJSnKRiRNx+pwTa30n4QDsUZO2EtEgJTJB25W51IF66kOGyjqddxh68yu594ylEXK+h15aWtKXAfV8Vpl0QOUYnOhk503QLuO9GziQefEppWf31vuIniyzwc6lT3+Ls4ALl87D8h7zVF+SuRHnGCqN4ma1LzTD0gXP8Ymh1vtQxXPoIKkozEktCcVhm0KYS6Ugoen8gtFkeQZjiqBzFneVxkZR9xl4l+Pt8o3ErtBy4GdFp0rGqyHECLwnoVb0CmjEhRjo0MQoxaZf+GUBHC6M9raiI9K9IX093LuFffm69tvYWbaLc6HFtoWC0yd0nidsZIjZPBTH7r4vtkKOdxLJkujKjTFRQKnfqPE3X1MmwU+3yqUohCnOuqrHxlVEDCEEdKdWjB6GJWjZyysv4r+DQLlcn2SwK6DtROf9+7DaYtOBcvR6EtkDwoOuw5QgmNb2TSiTcBWXO82qJ1bE="

